version: '3.1'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    restart: unless-stopped
    ports:
     - 8069:8069
    environment:
     - HOST=db
     - USER=odoo
     - PASSWORD=odoo
    volumes:
     - /opt/odoo-web-data:/var/lib/odoo
     - /opt/odoo-config:/etc/odoo
     - /opt/odoo-addons:/mnt/extra-addons   
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
     - POSTGRES_DB=postgres
     - POSTGRES_PASSWORD=odoo
     - POSTGRES_USER=odoo
     - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
     - /opt/odoo-db-data:/var/lib/postgresql/data/pgdata
