version: '2'
services:
  db:
    container_name: orbitalsystems_db
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - epmapat-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "$port_db:5432"
  web:
    container_name: orbitalsystems_odoo
    image: orbitalsystems_odoo:14.0
    build: ./
    depends_on:
      - db
    ports:
      - "$port:8069"
      - "$chat_port:8072"
    volumes:
      - orbitalsystems-web-data:/var/lib/odoo
      - ./docker:/etc/odoo/
      - ./addons:/mnt/extra-addons
volumes:
    orbitalsystems-web-data:
    orbitalsystems-db-data:
